version: '3'
services:
  web:
    image: httpd
    ports:
      - "8080:80"
    volumes:
       - ~/myLocalSyncFolder/:/source/
       - target:/usr/local/apache2/htdocs/ 
  sos-sync:
    image: sebastianzoll/docker-sos:latest
    volumes:
       - ~/myLocalSyncFolder/:/source/
       - target:/target/
volumes:
  target: